#pragma once

/* Base version of the WebKit Autoloader (WKAL) content.
 * Bump this when the autoloader frontend changes — it triggers the app-cache
 * update and also marks the matching WKALI installer build.
 *
 * Fork of itsPLK/ps5-webkit-autoloader. The "x" suffix marks the variant whose
 * bundled payload is ps5-unified-autoloader-x (embeds Payload Manager X). */
#define WKAL_VERSION "0.3.3x"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/wkali_version.h */
#include "wkali_version.h"

/* Network Settings — arbitrary port, chosen to avoid colliding with other
 * homebrew HTTP servers (must match the deeplink in assets/param.json.template) */
#define WKALI_PORT 18181

/* Title ID of the installed homescreen app ("WebKit Autoloader X").
 * MUST match "titleId" in assets/param.json.template. Distinct from upstream's
 * WKAL00001 so this fork installs alongside the official autoloader instead of
 * overwriting it — set both back to WKAL00001 for a true drop-in replacement. */
#define WKAL_TITLE_ID "WKLX00001"

/* Process identity — used to kill stale installer instances on startup */
#define WKALI_THREAD_NAME "wkali.elf"

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"

/* Logging (implementation in log.c) */
void wkali_log(const char *fmt, ...);
size_t wkali_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void wkali_log_wakeup(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
