#pragma once

/* Version of the WebKit Autoloader (WKAL) content. Bumping it triggers the
 * app-cache update and marks the matching WKALI installer build.
 *
 * Fork of itsPLK/ps5-webkit-autoloader. Scheme: <PLK version>.<fork build>x
 *
 *   0 . 3 . 0 . 4 x
 *   \_______/  |  \_ marks this as the Payload Manager X variant
 *       |      \____ ours: bump on every fork release
 *       \___________ upstream PLK's WKAL_VERSION, tracked verbatim
 *
 * So the first three components always state which PLK release this is based
 * on. When upstream bumps (e.g. to 0.3.1), take their number and reset the
 * fork build to 1 -> "0.3.1.1x". Only ever bump the last component for our own
 * changes. */
#define WKAL_VERSION "0.3.0.5x"

/* Full build version (stable: <base>, dev: <base>-dev-<hash|timestamp>),
 * generated by tools/gen_version.py — see include/wkali_version.h */
#include "wkali_version.h"

/* --- Coexistence -------------------------------------------------------
 *
 * Three builds must be installable on one console at the same time:
 *
 *   upstream PLK    WKAL00001  "WebKit Autoloader"  127.0.0.1:18181  cached
 *   this fork       WKLX00001  "Jailbreak"          127.0.0.1:18282  cached
 *   local variant   WKLL00001  "Jailbreak (Local)"  <LOCAL_HOST>     no cache
 *
 * The port is part of the page's origin, and AppCache is keyed by origin, so
 * it MUST differ from upstream's 18181. Sharing the port would mean sharing
 * one cache entry: whichever app was launched last would overwrite the other's
 * cached autoloader. The title ID must differ for the same reason at the app
 * level — same ID means one app overwrites the other.
 * ---------------------------------------------------------------------- */
#define WKALI_PORT 18282

/* Title ID and homescreen label of the installed app.
 *
 * WKAL_TITLE_ID must match "titleId" in the matching param template —
 * app_installer.c builds /user/app/<title_id>/... from this constant while the
 * metadata comes from the template. gen_version.py / gen_local_param.py keep
 * the deeplink in those templates in sync with WKALI_PORT and LOCAL_HOST.
 *
 * Define WKAL_VARIANT_LOCAL (make local) to build the shortcut-only variant
 * that points at a LAN host instead of the on-console cached autoloader. */
#ifdef WKAL_VARIANT_LOCAL
#define WKAL_TITLE_ID     "WKLL00001"
#define WKAL_APP_LABEL    "Jailbreak (Local)"
#define WKALI_THREAD_NAME "wkalil.elf"
#else
#define WKAL_TITLE_ID     "WKLX00001"
#define WKAL_APP_LABEL    "Jailbreak"
/* Process identity — used to kill stale installer instances on startup */
#define WKALI_THREAD_NAME "wkali.elf"
#endif

/* Routes */
#define ROUTE_INDEX "/"
#define ROUTE_INDEX_HTML "/index.html"
#define ROUTE_CACHE_MANIFEST "/cache.appcache"
#define ROUTE_INSTALL "/install"
#define ROUTE_VERSION "/version"

/* Logging (implementation in log.c) */
void wkali_log(const char *fmt, ...);
size_t wkali_wait_logs(size_t *pos, char *out_buf, size_t max_len);
void wkali_log_wakeup(void);

/* Notifications (declared in notification.h) */
#include "notification.h"
